name: Create Release ZIP
on:
  push:
    tags:
      - '*'

jobs:
  create-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Need this permission to create releases
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag info
        id: tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          # Check if this is a release candidate
          if [[ $TAG_NAME =~ .*-rc[0-9]+$ ]]; then
            echo "is_rc=true" >> $GITHUB_OUTPUT
          else
            echo "is_rc=false" >> $GITHUB_OUTPUT
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create temporary directory for zip files
        run: |
          mkdir zip_files
          # Copy all files except those to be excluded for non-RC releases
          if [ "${{ steps.tag.outputs.is_rc }}" = "false" ]; then
            echo "Creating zip without excluded files..."
            rsync -av \
              --exclude 'sample.txt' \
              --exclude 'sample/sample2.txt' \
              --exclude 'debug/' \
              ./ zip_files/
          else
            echo "Creating RC zip with all files..."
            rsync -av ./ zip_files/
          fi

      - name: Create ZIP archive
        run: |
          cd zip_files
          zip -r "../${{ steps.tag.outputs.tag_name }}.zip" .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.tag.outputs.tag_name }}.zip
          draft: false
          prerelease: ${{ steps.tag.outputs.is_rc }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}